apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationBackup
metadata:
  name: postgres-backup
  namespace: backup-lab
spec:
  backupLocation: internal-objectstore
  namespaces:
  - backup-lab
  reclaimPolicy: Retain
  selectors:
  preExecRule:
  postExecRule:
