apiVersion: stork.libopenstorage.org/v1alpha1
kind: ApplicationRestore
metadata:
  name: postgres-restore
  namespace: backup-lab
spec:
  backupName: <INSERT NAME OF BACKUP>
  backupLocation: internal-objectstore
