apiVersion: stork.libopenstorage.org/v1alpha1
kind: Migration
metadata:
  name: redis-migration
  namespace: kube-system
spec:
  clusterPair: dest-cluster
  includeResources: true
  startApplications: true
  namespaces:
  - redis
  purgeDeletedResources: false
