apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-cloudsnap-clone
  annotations:
    snapshot.alpha.kubernetes.io/snapshot: postgres-snapshot
spec:
  accessModes:
     - ReadWriteOnce
  storageClassName: stork-snapshot-sc
  resources:
    requests:
      storage: 2Gi
